-- | @katari.lock@ — the pinned resolution of every reachable dependency.
--
-- @
-- [lock]
-- version  = 1                    # lockfile format version
-- snapshot = "v0.1.0"             # mirrored from katari.toml (omitted for path/git-only projects)
--
-- [packages.list_utils]
-- source = "snapshot"
-- repo   = "https://github.com/.../list_utils"
-- ref    = "v0.2.1"
-- sha256 = "abc..."
--
-- [packages.local_fork]
-- source = "path"
-- path   = "../local_fork"        # no sha256: path deps are mutable on purpose
--
-- [packages.bleeding_edge]
-- source = "git"
-- repo   = "https://github.com/foo/bar"
-- rev    = "abc1234..."           # resolved full SHA
-- sha256 = "def..."
-- @
--
-- The lockfile is generated by @katari apply@ / @katari resolve@ and is meant to be committed so
-- every consumer gets the same byte-for-byte resolution.
module Katari.Project.Lockfile
  ( Lockfile (..),
    LockedPackage (..),
    LockedSource (..),
    lockfileFilename,
    parseLockfile,
    renderLockfile,
    loadLockfile,
    writeLockfile,
  )
where

import Data.Map.Strict (Map)
import Data.Text (Text)
import Katari.Project.Error (ProjectError)

-- | Conventional filename, sibling to @katari.toml@.
lockfileFilename :: FilePath
lockfileFilename = "katari.lock"

data Lockfile = Lockfile
  { -- | Current schema version (1 for now).
    version :: Int,
    -- | The snapshot id in effect when this lock was generated; 'Nothing' for path/git-only deps.
    snapshot :: Maybe Text,
    -- | Resolved entries keyed by dep name; serialised alphabetically for deterministic contents.
    packages :: Map Text LockedPackage
  }
  deriving (Show, Eq)

data LockedPackage = LockedPackage
  { name :: Text,
    source :: LockedSource
  }
  deriving (Show, Eq)

data LockedSource
  = LockedSnapshot
      { repo :: Text,
        ref :: Text,
        sha :: Text
      }
  | LockedPath {location :: FilePath}
  | LockedGit
      { url :: Text,
        rev :: Text,
        sha :: Text
      }
  deriving (Show, Eq)

-- | Parse the textual contents of @katari.lock@.
parseLockfile :: FilePath -> Text -> Either ProjectError Lockfile
parseLockfile = error "TODO: Katari.Project.Lockfile.parseLockfile"

-- | Render a 'Lockfile' to deterministic, byte-stable TOML.
renderLockfile :: Lockfile -> Text
renderLockfile = error "TODO: Katari.Project.Lockfile.renderLockfile"

loadLockfile :: FilePath -> IO (Either ProjectError Lockfile)
loadLockfile = error "TODO: Katari.Project.Lockfile.loadLockfile"

-- | Write a 'Lockfile' to @path@, overwriting any existing file.
writeLockfile :: FilePath -> Lockfile -> IO ()
writeLockfile = error "TODO: Katari.Project.Lockfile.writeLockfile"
