snapshot: lts-22.44 # GHC 9.6.7

packages:
  - haskell/katari
  - haskell/katari-compiler
  - haskell/katari-project
  - haskell/katari-lsp

ghc-options:
  "$locals": -Wall -Wcompat -Wincomplete-record-updates
    -Wincomplete-uni-patterns -Wmissing-home-modules
    -Wredundant-constraints

extra-deps:
  - tomland-1.3.3.3
  - validation-selective-0.2.0.0
