-- | The @katari mcp pull@ codegen contract, at two altitudes:
--
--   * a GOLDEN test — one fixture listing to exact generated text, so any template drift is a
--     conscious diff (and the wire-form asymmetry stays visible in review: a fallback parameter is
--     inserted as-is, a fully-mapped one through @json.encode@; decoding is all-or-nothing);
--   * ROUND-TRIP tests — every generated module must COMPILE against the real wired-in stdlib
--     (the exact @Katari.Compile.compile@ entry the CLI's check/build commands drive), across the
--     interesting shapes: a simple tool, optional parameters, a fallback parameter, mappable and
--     unmappable output schemas, and name-mangling collisions.
module Katari.Cli.McpCodegenSpec (spec) where

import Control.Monad (when)
import Data.Aeson qualified as Aeson
import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.Encoding qualified as TextEncoding
import Katari.Cli.McpCodegen (McpListing, PullContext (..), renderBindingModule)
import Katari.Compile qualified as Compile
import Katari.Data.ModuleName (moduleNameFromSegments)
import Katari.Diagnostics (hasErrors, renderDiagnostics)
import Test.Hspec

-- | Decode a fixture listing (the exact JSON `katari-mcp list-tools` prints). A malformed fixture
-- is a test bug — fail the test rather than propagate a bogus listing.
listingOf :: Text -> IO McpListing
listingOf raw = case Aeson.eitherDecodeStrict' (TextEncoding.encodeUtf8 raw) of
  Left decodeError -> fail ("fixture listing did not decode: " <> decodeError)
  Right listing -> pure listing

pullContext :: PullContext
pullContext =
  PullContext
    { url = "https://mcp.example.test/mcp",
      outPath = "src/github.ktr"
    }

render :: Text -> IO Text
render fixture = renderBindingModule pullContext <$> listingOf fixture

-- | Compile one generated module against the real stdlib and expect zero error diagnostics; on
-- failure the rendered module and the diagnostics are the assertion message, so a grammar or type
-- drift is diagnosable straight from the test output.
shouldCompile :: Text -> Expectation
shouldCompile rendered = do
  let sources = Map.singleton (moduleNameFromSegments ["github"]) rendered
      result = Compile.compile Compile.CompileInput {Compile.sources = sources}
  when (hasErrors result.diagnostics) $
    expectationFailure
      ( "the generated module does not compile:\n"
          <> Text.unpack (renderDiagnostics result.diagnostics)
          <> "\n--- generated module ---\n"
          <> Text.unpack rendered
      )

---------------------------------------------------------------------------------------------------
-- Fixtures
---------------------------------------------------------------------------------------------------

-- | Two tools: a fully typed one (mapped params, mapped output, one optional param, one fallback
-- param) and a text-ish one with no output schema — the golden covers both output plans at once.
goldenFixture :: Text
goldenFixture =
  "{\"tools\": [\
  \  {\"name\": \"get-issue\",\
  \   \"description\": \"Fetch one issue.\\nSlow on \\\"cold\\\" repos.\",\
  \   \"inputSchema\": {\"type\": \"object\",\
  \                     \"properties\": {\"owner\": {\"type\": \"string\"},\
  \                                      \"repo\": {\"type\": \"string\"},\
  \                                      \"labels\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}},\
  \                                      \"filter\": {\"enum\": [\"open\", \"closed\"]}},\
  \                     \"required\": [\"owner\", \"repo\"]},\
  \   \"outputSchema\": {\"type\": \"object\",\
  \                      \"properties\": {\"number\": {\"type\": \"integer\"},\
  \                                       \"title\": {\"type\": \"string\"},\
  \                                       \"assignee\": {\"anyOf\": [{\"type\": \"string\"}, {\"type\": \"null\"}]}},\
  \                      \"required\": [\"number\", \"title\"]}},\
  \  {\"name\": \"ping\", \"description\": \"\", \"inputSchema\": {\"type\": \"object\"}}\
  \]}"

golden :: Text
golden =
  Text.unlines
    [ "// Generated by `katari mcp pull --url https://mcp.example.test/mcp --out src/github.ktr`.",
      "// Regenerate instead of editing.",
      "//",
      "// Type mapping (JSON Schema -> Katari), all-or-nothing per parameter and per tool output:",
      "//   - string / integer / number / boolean / null map directly; array -> array[T];",
      "//   - an object with properties -> an object type (a non-required property becomes a `?` field);",
      "//   - an object with only schema-valued additionalProperties -> record[T];",
      "//   - an anyOf whose members all map -> a union;",
      "//   - everything else (enum / const, allOf / oneOf, tuples, open or",
      "//     unmodelled schemas) falls back to `json.json`.",
      "// All-or-nothing on the PARAMETER side is the wire-form asymmetry: `json.encode` speaks the value",
      "// WIRE form, so a `json.json` nested inside a typed parameter would embed as its `$constructor` tree,",
      "// not the raw fragment the server expects — a fallback parameter is therefore inserted into the",
      "// arguments tree as-is (it already is a tree). The output side has no such asymmetry: `mcp.call[url,",
      "// T]` decodes the reply against `T` in the runtime, so a fully-mapped outputSchema instantiates `T`",
      "// to its type (decoded, `json.decode_error` on a mismatch) and any other tool instantiates `T` to",
      "// `json.json` (the raw reply as a tree).",
      "",
      "// The declared output of `get-issue`.",
      "type get_issue_output = {assignee?: string | null, number: integer, title: string}",
      "",
      "@\"Open the pulled MCP server's tools for the extent of @continuation@ — as `let tools : {...} = use github.with_tools(auth = ...)` (a `use` binder carries an explicit type annotation). Establishes a `provide` scope over `https://mcp.example.test/mcp`, hands @continuation@ the typed tools closed over the connection, and discharges the scope on return. `auth` is `mcp.headers(values = ...)` for header or anonymous access, or `mcp.oauth(name = \\\"...\\\")` for a credential established by `katari mcp login`.\"",
      "agent with_tools[R, effect E](",
      "  auth: mcp.auth,",
      "  continuation: agent (value: {",
      "    get_issue: agent(filter?: json.json, labels?: array[string], owner: string, repo: string) -> get_issue_output with io | mcp.scope[\"https://mcp.example.test/mcp\"] | prelude.throw[mcp.server_error | mcp.auth_error | json.decode_error],",
      "    ping: agent(arguments: json.json) -> json.json with io | mcp.scope[\"https://mcp.example.test/mcp\"] | prelude.throw[mcp.server_error | mcp.auth_error | json.decode_error],",
      "  }) -> R with E | mcp.scope[\"https://mcp.example.test/mcp\"],",
      ") -> R with io | E {",
      "  let tools : mcp.toolbox[\"https://mcp.example.test/mcp\"] = use mcp.provide(url = \"https://mcp.example.test/mcp\", auth = auth)",
      "",
      "  @\"Fetch one issue.\\nSlow on \\\"cold\\\" repos.\" agent get_issue(filter: json.json | null ?= null, labels: array[string] | null ?= null, owner: string, repo: string) -> get_issue_output with io | mcp.scope[\"https://mcp.example.test/mcp\"] | prelude.throw[mcp.server_error | mcp.auth_error | json.decode_error] {",
      "    let arguments_0 = record.empty()",
      "    let arguments_1 = match (filter) {",
      "      case null -> arguments_0",
      "      case present -> record.set(target = arguments_0, key = \"filter\", value = present)",
      "    }",
      "    let arguments_2 = match (labels) {",
      "      case null -> arguments_1",
      "      case present -> record.set(target = arguments_1, key = \"labels\", value = json.encode(value = present))",
      "    }",
      "    let arguments_3 = record.set(target = arguments_2, key = \"owner\", value = json.encode(value = owner))",
      "    let arguments_4 = record.set(target = arguments_3, key = \"repo\", value = json.encode(value = repo))",
      "    mcp.call[\"https://mcp.example.test/mcp\", get_issue_output](url = \"https://mcp.example.test/mcp\", auth = auth, tool = \"get-issue\", arguments = json.json_object(entries = arguments_4))",
      "  }",
      "",
      "  agent ping(arguments: json.json) -> json.json with io | mcp.scope[\"https://mcp.example.test/mcp\"] | prelude.throw[mcp.server_error | mcp.auth_error | json.decode_error] {",
      "    mcp.call[\"https://mcp.example.test/mcp\", json.json](url = \"https://mcp.example.test/mcp\", auth = auth, tool = \"ping\", arguments = arguments)",
      "  }",
      "",
      "  continuation(value = {",
      "    get_issue = get_issue,",
      "    ping = ping,",
      "  })",
      "}"
    ]

manglingFixture :: Text
manglingFixture =
  "{\"tools\": [\
  \  {\"name\": \"get-issue\", \"inputSchema\": {\"type\": \"object\", \"properties\": {\"type\": {\"type\": \"string\"}, \"maxResults\": {\"type\": \"integer\"}}, \"required\": [\"type\"]}},\
  \  {\"name\": \"get_issue\", \"inputSchema\": {\"type\": \"object\", \"properties\": {\"x\": {\"type\": \"number\"}}, \"required\": [\"x\"]}},\
  \  {\"name\": \"match\", \"inputSchema\": {\"type\": \"object\", \"properties\": {\"url\": {\"type\": \"string\"}}, \"required\": [\"url\"]}},\
  \  {\"name\": \"3d-render\", \"inputSchema\": {\"type\": \"object\", \"properties\": {\"scene\": {\"type\": \"string\"}}, \"required\": [\"scene\"]}},\
  \  {\"name\": \"json\", \"inputSchema\": {\"type\": \"object\", \"properties\": {\"value\": {\"type\": \"string\"}}, \"required\": [\"value\"]}}\
  \]}"

outputShapesFixture :: Text
outputShapesFixture =
  "{\"tools\": [\
  \  {\"name\": \"typed\",\
  \   \"inputSchema\": {\"type\": \"object\", \"properties\": {\"q\": {\"type\": \"string\"}}, \"required\": [\"q\"]},\
  \   \"outputSchema\": {\"type\": \"object\",\
  \                      \"properties\": {\"hits\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"properties\": {\"id\": {\"type\": \"integer\"}}, \"required\": [\"id\"]}},\
  \                                       \"scores\": {\"type\": \"object\", \"additionalProperties\": {\"type\": \"number\"}}},\
  \                      \"required\": [\"hits\"]}},\
  \  {\"name\": \"partly-typed\",\
  \   \"inputSchema\": {\"type\": \"object\", \"properties\": {\"q\": {\"type\": \"string\"}}, \"required\": [\"q\"]},\
  \   \"outputSchema\": {\"type\": \"object\",\
  \                      \"properties\": {\"title\": {\"type\": \"string\"}, \"payload\": {}},\
  \                      \"required\": [\"title\", \"payload\"]}},\
  \  {\"name\": \"reserved-field\",\
  \   \"inputSchema\": {\"type\": \"object\", \"properties\": {\"q\": {\"type\": \"string\"}}, \"required\": [\"q\"]},\
  \   \"outputSchema\": {\"type\": \"object\",\
  \                      \"properties\": {\"type\": {\"type\": \"string\"}},\
  \                      \"required\": [\"type\"]}}\
  \]}"

---------------------------------------------------------------------------------------------------
-- Spec
---------------------------------------------------------------------------------------------------

spec :: Spec
spec = describe "katari mcp pull codegen" $ do
  describe "golden" $ do
    it "renders the fixture listing to the exact module text" $ do
      rendered <- render goldenFixture
      rendered `shouldBe` golden

    it "the golden module compiles against the real stdlib" $ do
      rendered <- render goldenFixture
      shouldCompile rendered

  describe "wire-form asymmetry" $ do
    it "embeds a fully-mapped parameter through json.encode and a fallback parameter as-is" $ do
      rendered <- render goldenFixture
      -- (a) `labels` maps (array[string]) — it must go through the wire-form embedding.
      rendered `shouldSatisfy` Text.isInfixOf "key = \"labels\", value = json.encode(value = present)"
      -- (a) `filter` is an enum — a fallback — so it must be inserted AS-IS (already a tree); an
      -- encode here would ship the `$constructor` wire tree instead of the raw fragment.
      rendered `shouldSatisfy` Text.isInfixOf "key = \"filter\", value = present"
      rendered `shouldSatisfy` (not . Text.isInfixOf "key = \"filter\", value = json.encode")

    it "decodes only a fully-mapped outputSchema; any fallback inside keeps the raw reply" $ do
      rendered <- render outputShapesFixture
      -- (b) `typed` maps everywhere (nested array/object/record) — its `T` is the mapped type, so the
      -- runtime decodes the reply against it (no trailing `json.decode` anywhere anymore).
      rendered `shouldSatisfy` Text.isInfixOf "type typed_output = {hits: array[{id: integer}], scores?: record[number]}"
      rendered `shouldSatisfy` Text.isInfixOf "mcp.call[\"https://mcp.example.test/mcp\", typed_output](url ="
      rendered `shouldSatisfy` (not . Text.isInfixOf "json.decode[")
      -- (b) `partly-typed` has ONE untyped field — the whole output stays `json.json` (the `T` argument).
      rendered `shouldSatisfy` (not . Text.isInfixOf "partly_typed_output")
      rendered `shouldSatisfy` Text.isInfixOf "mcp.call[\"https://mcp.example.test/mcp\", json.json](url = \"https://mcp.example.test/mcp\", auth = auth, tool = \"partly-typed\""
      -- (b) a field named by a reserved word cannot label an object type — also raw.
      rendered `shouldSatisfy` (not . Text.isInfixOf "reserved_field_output")
      shouldCompile rendered

  describe "name mangling" $ do
    it "assigns deterministic identifiers (snake_case, digit prefix, reserved suffix, collision bump)" $ do
      rendered <- render manglingFixture
      rendered `shouldSatisfy` Text.isInfixOf "agent get_issue("
      -- The later original name loses the collision deterministically (sorted by original name).
      rendered `shouldSatisfy` Text.isInfixOf "agent get_issue_2("
      rendered `shouldSatisfy` Text.isInfixOf "agent match_("
      rendered `shouldSatisfy` Text.isInfixOf "agent _3d_render("
      -- `json` would shadow the default-import qualifier every body references — bumped.
      rendered `shouldSatisfy` Text.isInfixOf "agent json_2("
      -- The ORIGINAL names still ride in the tool arguments.
      rendered `shouldSatisfy` Text.isInfixOf "tool = \"get-issue\""
      rendered `shouldSatisfy` Text.isInfixOf "tool = \"get_issue\""
      rendered `shouldSatisfy` Text.isInfixOf "tool = \"3d-render\""
      rendered `shouldSatisfy` Text.isInfixOf "tool = \"json\""
      -- A parameter named by a reserved word mangles, but its record.set key stays original.
      rendered `shouldSatisfy` Text.isInfixOf "type_: string"
      rendered `shouldSatisfy` Text.isInfixOf "key = \"type\", value = json.encode(value = type_)"
      -- camelCase lowers to snake_case, key stays original.
      rendered `shouldSatisfy` Text.isInfixOf "max_results: integer | null ?= null"
      rendered `shouldSatisfy` Text.isInfixOf "key = \"maxResults\""
      -- A parameter named `url` would shadow the closed-over connection — bumped.
      rendered `shouldSatisfy` Text.isInfixOf "url_2: string"
      rendered `shouldSatisfy` Text.isInfixOf "key = \"url\", value = json.encode(value = url_2)"

    it "the mangling module compiles against the real stdlib" $ do
      rendered <- render manglingFixture
      shouldCompile rendered

  describe "degenerate listings" $ do
    it "an empty listing still renders a compiling module" $ do
      rendered <- render "{\"tools\": []}"
      shouldCompile rendered
