name: katari-cli
version: 0.1.0.0
author: yukikurage
license: MIT

executables:
  katari:
    main: Main.hs
    source-dirs: app
    dependencies:
      - base >= 4.18 && < 5
      - katari-compiler
      - optparse-applicative
      - text
      - bytestring
      - containers
      - directory
      - filepath
      - aeson

default-extensions:
  - GHC2021
  - OverloadedStrings
  - LambdaCase
