// StepCtx: the writable handle a thread op uses to mutate state and emit
// side-effects during a single internal-event dispatch.
//
// `state` is an Immer draft that the op mutates as if it were plain
// data — Immer captures the patches that the runner translates into
// domain Diff[].
//
// Outbound events / errors / logs are appended to plain arrays. The
// runner accumulates these across the queue drain and packs them into
// the final Result.
//
// Internal events generated by an op are pushed to the engine's queue;
// the runner picks them up on the next iteration of its drain loop.

import type { Draft } from "immer";
import type { EngineError } from "./errors.js";
import type { Event, InternalEventPayload } from "./event.js";
import type { LogEntry, LogLevel } from "./logger.js";
import type { State } from "./state.js";

export interface StepCtx {
  /** Mutable draft of the engine state for this step. */
  readonly state: Draft<State>;
  /** Schedule another internal event to be processed in this applyEvent. */
  enqueue(event: InternalEventPayload): void;
  /** Push an outbound event (caller will forward externally). */
  emit(event: Event): void;
  /** Append a log entry. */
  log(level: LogLevel, message: string, context?: Record<string, unknown>): void;
  /** Record a recoverable error without aborting the step loop. */
  recordError(err: EngineError): void;
}

/**
 * Bag of side-effect accumulators that survive the Immer `produce` boundary.
 * The runner allocates one per `applyEvent` invocation and threads it
 * through every step.
 */
export type StepBuffers = {
  queue: InternalEventPayload[];
  outbound: Event[];
  errors: EngineError[];
  logs: LogEntry[];
};

export function emptyBuffers(): StepBuffers {
  return { queue: [], outbound: [], errors: [], logs: [] };
}

/** Build a StepCtx that backs onto the given draft + buffers. */
export function makeStepCtx(
  draft: Draft<State>,
  buffers: StepBuffers,
): StepCtx {
  return {
    state: draft,
    enqueue(event) {
      buffers.queue.push(event);
    },
    emit(event) {
      buffers.outbound.push(event);
    },
    log(level, message, context) {
      buffers.logs.push({ level, message, context });
    },
    recordError(err) {
      buffers.errors.push(err);
    },
  };
}
