// StepCtx: the writable handle a thread op uses to mutate state and emit
// side-effects during a single internal-event dispatch.
//
// `state` is an Immer draft that the op mutates as if it were plain
// data — Immer commits the structural change when `produce` returns.
//
// Outbound events / errors / logs are appended to plain arrays. The
// runner accumulates these across the queue drain and packs them into
// the final Result.
//
// Internal events generated by an op are pushed to the engine's queue;
// the runner picks them up on the next iteration of its drain loop.

import type { Draft } from "immer";
import type { Event, InternalEventPayload } from "./event.js";
import type { LogEntry, LogLevel } from "./logger.js";
import type { State } from "./state.js";

export interface StepCtx {
  /** Mutable draft of the engine state for this step. */
  readonly state: Draft<State>;
  /** Schedule another internal event to be processed in this applyEvent. */
  enqueue(event: InternalEventPayload): void;
  /** Push an outbound event (caller will forward externally). */
  emit(event: Event): void;
  /** Append a log entry. */
  log(level: LogLevel, message: string, context?: Record<string, unknown>): void;
}

/**
 * Bag of side-effect accumulators that survive the Immer `produce` boundary.
 * The runner allocates one per `applyEvent` invocation and threads it
 * through every step.
 */
export type StepBuffers = {
  queue: InternalEventPayload[];
  outbound: Event[];
  logs: LogEntry[];
};

export function emptyBuffers(): StepBuffers {
  return { queue: [], outbound: [], logs: [] };
}

/** Build a StepCtx that backs onto the given draft + buffers. */
export function makeStepCtx(
  draft: Draft<State>,
  buffers: StepBuffers,
): StepCtx {
  return {
    state: draft,
    enqueue(event) {
      // Detach from the Immer draft graph: queue events live across
      // step boundaries; if any field is still a proxy when the draft's
      // produce returns, it gets revoked and the next dispatch reads
      // garbage.
      //
      // We use JSON round-trip rather than `structuredClone` (= V8
      // native, ~2-3× faster) because thread ops construct events as
      // plain objects whose nested `args` may still contain Immer-draft
      // proxies. structuredClone refuses internal proxy slots; JSON
      // serialise/parse walks the proxy via .toJSON() and produces a
      // detached plain object. Immer's `current()` would also work but
      // only on a top-level draft, and we'd need a deep walk to find
      // the nested proxies — same cost.
      //
      // A faster alternative is to refactor op code so events never
      // embed draft references in the first place (= always copy via
      // `current()` at the source). Tracked as a v0.2.0 perf RFC; the
      // JSON round-trip is the safe baseline.
      buffers.queue.push(detach(event));
    },
    emit(event) {
      buffers.outbound.push(detach(event));
    },
    log(level, message, context) {
      buffers.logs.push({
        level,
        message,
        context: context !== undefined ? detach(context) : undefined,
      });
    },
  };
}

function detach<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}
