// StepCtx: the writable handle a thread op uses to mutate state and emit
// side-effects during a single internal-event dispatch.
//
// `state` is the live `State` object — ops mutate it directly. No
// Immer involvement: every tick creates a fresh `CoreModule` instance
// with state freshly loaded from the DB, so half-modified state on a
// thrown op is discarded with the instance (tx rollback handles the
// DB side).
//
// Outbound events / errors / logs are appended to plain arrays. The
// runner accumulates these across the queue drain and packs them into
// the final Result.
//
// Internal events generated by an op are pushed to the engine's queue;
// the runner picks them up on the next iteration of its drain loop.

import type { Event, InternalEventPayload } from "./event.js";
import type { LogEntry, LogLevel } from "./logger.js";
import type { State } from "./state.js";
import type { BytesRep, RefRep } from "./value.js";

/**
 * Fetch the bytes of a content-addressed ref. Injected by the host
 * (ValueStore-backed) so the pure engine stays I/O-free at the type level.
 * The fetch is a deterministic function of the content hash, so the engine
 * remains deterministic-but-async (runtime-architecture §5).
 */
export type RefFetcher = (rep: RefRep) => Promise<Uint8Array>;

/**
 * Write bytes to the content store and return their ref. Injected by the host
 * (ValueStore-backed), symmetric to {@link RefFetcher}. Used by make-closure to
 * persist a closure's captured env to a blob BEFORE handing back its ref — so a
 * ref never exists without its referent. Content-addressed ⇒ deterministic.
 */
export type RefPutter = (bytes: Uint8Array) => Promise<RefRep>;

/**
 * Default fetcher for when no value store is wired. v0.1.0 (pre-E1) produces
 * no refs in CORE state — promotion lands with the shard storage — so this is
 * never actually hit; it throws loudly if a ref unexpectedly appears.
 */
export const noRefFetcher: RefFetcher = () => {
  throw new Error("engine: ref materialize requested but no value store is wired");
};

/** Default putter for when no value store is wired — throws loudly if a
 *  closure crosses (make-closure needs to persist its env). */
export const noRefPutter: RefPutter = () => {
  throw new Error("engine: closure persist requested but no value store is wired");
};

export interface StepCtx {
  /** Live engine state for this step (mutated in place). */
  readonly state: State;
  /** Schedule another internal event to be processed in this applyEvent. */
  enqueue(event: InternalEventPayload): void;
  /** Push an outbound event (caller will forward externally). */
  emit(event: Event): void;
  /** Append a log entry. */
  log(level: LogLevel, message: string, context?: Record<string, unknown>): void;
  /**
   * Materialize a byte-sequence rep to its bytes. Inline → resolved
   * immediately; ref → fetched via the injected `RefFetcher`. Used by the
   * content-transform prims (concat / format) that need the actual bytes;
   * == / match / length never call this (hash / metadata only).
   */
  materialize(rep: BytesRep): Promise<Uint8Array>;
  /**
   * Persist bytes to the content store and return their ref. Used by
   * make-closure to freeze a closure's captured env into a blob. Symmetric to
   * `materialize`; the write happens within the host's quantum transaction.
   */
  putBlob(bytes: Uint8Array): Promise<RefRep>;
}

/**
 * Bag of side-effect accumulators threaded through every step. The
 * runner allocates one per `applyEvent` invocation. Outbound events
 * and logs are collected here; the internal-event queue lives here
 * too, so an op pushing to `queue` schedules work for the next
 * iteration of the drain loop.
 */
export type StepBuffers = {
  queue: InternalEventPayload[];
  outbound: Event[];
  logs: LogEntry[];
};

export function emptyBuffers(): StepBuffers {
  return { queue: [], outbound: [], logs: [] };
}

/** Build a StepCtx that backs onto the given state + buffers. */
export function makeStepCtx(
  state: State,
  buffers: StepBuffers,
  fetchRef: RefFetcher = noRefFetcher,
  putRef: RefPutter = noRefPutter,
): StepCtx {
  return {
    state,
    enqueue(event) {
      buffers.queue.push(event);
    },
    emit(event) {
      buffers.outbound.push(event);
    },
    log(level, message, context) {
      buffers.logs.push({ level, message, context });
    },
    materialize(rep) {
      if (rep.kind === "inline") return Promise.resolve(new TextEncoder().encode(rep.text));
      return fetchRef(rep);
    },
    putBlob(bytes) {
      return putRef(bytes);
    },
  };
}
