import { katari } from "@katari-lang/port";

// `makeGreeting` (registers as `main.makeGreeting`): produce a file from generated bytes. `context.uploadBlob`
// POSTs the bytes to the runtime over the blob side channel and returns the file handle, which the runtime
// lifts into the `file` value the program receives.
katari.agent("makeGreeting", async (argument, context) => {
  const name =
    typeof argument === "object" &&
    argument !== null &&
    !Array.isArray(argument) &&
    typeof argument.name === "string"
      ? argument.name
      : "stranger";
  const bytes = new TextEncoder().encode(`Hello, ${name}!`);
  return context.uploadBlob(bytes, { contentType: "text/plain" });
});

// `byteLength` (registers as `main.byteLength`): read a received file's bytes back and return their length.
// The argument's `content` is the file handle (`{ $ref, ... }`); `context.downloadBlob` pulls the bytes over
// the same side channel.
katari.agent("byteLength", async (argument, context) => {
  if (
    typeof argument !== "object" ||
    argument === null ||
    Array.isArray(argument) ||
    typeof argument.content !== "object" ||
    argument.content === null ||
    Array.isArray(argument.content) ||
    typeof argument.content.$ref !== "string"
  ) {
    throw new Error("byteLength: expected a { content: file } argument");
  }
  const bytes = await context.downloadBlob(argument.content.$ref);
  return bytes.length;
});
